[package]
authors = ["zerosign <r1nlx0@gmail.com>"]
name = "central"
version = "0.1.0"

[dependencies]
# crossbeam = "0.3.0"
env_logger = "0.4.3"
# lazy_static = "0.2.8"
log = "0.3.8"
rand = "0.3.16"
redis = "0.8.0"
